version: "3"
services:
  jupyterhub:
    build: ./jupyterhub
    environment:
      - OAUTH_CALLBACK_URL=https://subd.domain.com/hub/oauth_callback
      - GITHUB_CLIENT_ID=asdfasdfasdf
      - GITHUB_CLIENT_SECRET=asdfasdfasdfasdfasdf
      - VIRTUAL_HOST=sub.domain.com
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=sub.domain.com
      - LETSENCRYPT_EMAIL=admin@domain.com
      - JUPYTERHUB_ADMIN=githubusername
    volumes:
      - jupyter_hub:/srv/jupyterhub
    restart: always
    networks:
      - proxy-tier
      - default
  minecraft:
    image: itzg/minecraft-server
    volumes:
      - minecraft:/data
    ports:
      - 25565:25565
    expose:
      - "4711"
    environment:
      - EULA=TRUE
      - ENABLE_COMMAND_BLOCK=TRUE
      - SNOOPER_ENABLED=FALSE
      - SPAWN_MONSTERS=FALSE
      - SPAWN_NPCS=TRUE
      - SPAWN_ANIMALS=TRUE
      - MODE=creative
      - PVP=FALSE
      - TYPE=SPIGOT
      - VERSION=1.13.1
      - MODS=https://github.com/zhuowei/RaspberryJuice/raw/master/jars/raspberryjuice-1.11.jar
      - MAX_PLAYERS=25
    restart: always
    command: --noconsole
    networks:
      - default
  proxy:
    image: jwilder/nginx-proxy:alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier
  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - proxy
volumes:
  jupyter_hub:
  minecraft:
  vhost.d:
  html:
  certs:

networks:
  proxy-tier: